### ISSUE TITLE
Cannot import 'meteor/**'

### ISSUE THREAD

**Issue by amandapouget** [pcorey/hello-meteor-modules#1]
Hi,

I'm new to Meteor and setting up a project. I don't want to wait forever to restart the app to run unit tests, either, which is what happens with the standard solution. I'm thinking about implementing this one as you described in your blog post, and have gotten far enough to hit the predictable roadblocks.

"Cannot find module 'meteor/meteor' -> resolve with dependency injection, passing a Meteor-like object into the constructor. Ok, makes sense. But what about:
"Cannot find module 'meteor/mongo' -> ...

Is this really worth it? It just feels like I'm fighting to go upstream here. Now I need to pass the constructor a fake database, too... ? Not sure that mocking things everywhere is inherently better than dealing with slow app restarts for browser-based testing.

**Comment by pcorey** [comment]
Hey Mandy,

You're right. Manually doing dependency injection like I described in my post can be a pain. The value gained by doing that kind of thing is questionable when you look at the amount of work and maintenance that goes into it.

Another (better) alternative may be to import things as you normally would (`import { Meteor} from "meteor/meteor";`), but then hook and mock those imports in your tests where you see fit.

Stephen Meijer (@smeijer) made an awesome post about this recently on the Meteor forums. [Check it out](https://forums.meteor.com/t/meteor-1-3-testing-with-meteor-meteor-x-package-imports/21009) and let me know if that works better with your situation!

I'm planning on writing this up in an update to my [Unit Testing with Meteor 1.3](http://blog.east5th.co/2015/12/21/unit-testing-with-meteor-1.3/) post sometime in the near future.

**Comment by amandapouget** [comment]
Pete,

I really appreciate your reply since we are using Meteor with a client
project and I haven't been able to find much else written about OO design
or TDD and Meteor.  I will check out the resource you mentioned and look
forward to your blog post. Thanks!

Amanda

**Comment by pcorey** [comment]
Hey @mandysimon88,

I just put out a new post that goes over (at a high level) using Testdouble.js to mock Meteor-style imports. Hopefully it will help you out, or give you some ideas moving forward:

http://blog.east5th.co/2016/05/02/meteor-unit-testing-with-testdoublejs/

**Comment by amandapouget** [comment]
Thanks, Pète!
